# -*- coding: utf-8 -*-
"""HCES_2023.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u8fB9rw4YMYniAyirCK__y_8HKF0GhtM
"""

import pandas as pd
#Read Excel, skipping the title row (use row 1 as header)
file_path='/content/HCES_2023_24_Imputation_Rate.xlsx'
df= pd.read_excel(file_path, header=1)
# Quick peek
print(df.head)
df.head(3)

print(df.isnull().sum())

df.dropna(how="all",inplace=True)

#  Numeric Columns
num_cols = ['sector','st','Questionnaire Item',
            'Rate_per_unit (Mode based)','Rate_per_unit (25th Percentile based)']

for col in num_cols:
  median = df[col].median()
  df[col].fillna(median, inplace=True)

# Categorical/Text Columns
df['Free Item Description'] = df['Free Item Description'].fillna('Unknown')
df['Item considered for rate computation'] = (
    df['Item considered for rate computation']
    .fillna(df['Item considered for rate computation'].mode()[0])
)

from sklearn.preprocessing import MinMaxScaler, StandardScaler

scalers = {
    'minmax': MinMaxScaler(),
    'zscore': StandardScaler()
}

scaled_frames = {}
for name, scaler in scalers.items():
  scaled = scaler.fit_transform(df[num_cols])
  scaled_frames[name] = pd.DataFrame(
      scaled, columns=[f"{c}_{name}" for c in num_cols]
      )

df=pd.concat([df, scaled_frames['minmax'], scaled_frames['zscore']],axis=1)
# e.g., df[['sector_minmax','sector_zscore]].head(2)

Q1 = df ['Rate_per_unit (Mode based)'].quantile(0.25)
Q3 = df ['Rate_per_unit (Mode based)'].quantile(0.75)
IQR = Q3 - Q1

lower,upper = Q1 - 1.5 * IQR, Q3 + 1.5*IQR
outliers = df [
    (df['Rate_per_unit (Mode based)']<lower) |
    (df['Rate_per_unit (Mode based)']>upper)
]
print(f"Outliers detected: {len(outliers)} rows")
