# -*- coding: utf-8 -*-
"""Outliers removing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nueK2nPoMkmZZORdPKbSE_CEN0h_RQVI
"""



"""We’ll work with HCES_2023_24_Imputation_Rate.xlsx, which contains state‑ and sector‑wise imputed rates for free‑of‑cost food items.

Key columns (after cleaning headers):

sector (numeric code)

st (state code)

Questionnaire Item (numeric ID of item)

Free Item Description (text)

Item considered for rate computation (categorical/list)

Rate_per_unit (Mode based) (numeric target)

Rate_per_unit (25th Percentile based) (numeric)


"""

import pandas as pd

# Read Excel, skipping the title row (use row 1 as header)
file_path = '/content/HCES_2023_24_Imputation_Rate.xlsx'
df = pd.read_excel(file_path, header=1)

# Quick peek
print(df.shape)
df.head(3)

print(df.isnull().sum())

df.dropna(how='all', inplace=True)

# Numeric columns
num_cols = ['sector', 'st', 'Questionnaire Item',
            'Rate_per_unit (Mode based)',
            'Rate_per_unit (25th Percentile based)']

for col in num_cols:
    median = df[col].median()
    df[col].fillna(median, inplace=True)

# Categorical/Text columns
df['Free Item Description'] = df['Free Item Description'].fillna('Unknown')
df['Item considered for rate computation'] = (
    df['Item considered for rate computation']
      .fillna(df['Item considered for rate computation'].mode()[0])
)

from sklearn.preprocessing import MinMaxScaler, StandardScaler

scalers = {
    'minmax': MinMaxScaler(),
    'zscore': StandardScaler()
}

scaled_frames = {}
for name, scaler in scalers.items():
    scaled = scaler.fit_transform(df[num_cols])
    scaled_frames[name] = pd.DataFrame(
        scaled,
        columns=[f"{c}_{name}" for c in num_cols]
    )

df = pd.concat([df, scaled_frames['minmax'], scaled_frames['zscore']], axis=1)
# e.g., df[['sector_minmax','sector_zscore']].head(2)

Q1 = df['Rate_per_unit (Mode based)'].quantile(0.25)
Q3 = df['Rate_per_unit (Mode based)'].quantile(0.75)
IQR = Q3 - Q1

lower, upper = Q1 - 1.5*IQR, Q3 + 1.5*IQR
outliers = df[
    (df['Rate_per_unit (Mode based)'] < lower) |
    (df['Rate_per_unit (Mode based)'] > upper)
]
print(f"Outliers detected: {len(outliers)} rows")

df['Rate_mode_capped'] = df['Rate_per_unit (Mode based)'].clip(lower, upper)

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

# Features & target
X = df[['sector','st','Questionnaire Item']]
y = df['Rate_per_unit (Mode based)']

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Fit linear model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict & evaluate
y_pred = model.predict(X_test)
print("R² score:        ", r2_score(y_test, y_pred))
print("RMSE:            ", mean_squared_error(y_test, y_pred))

# Examine coefficients
coeff_df = pd.DataFrame({
    'feature': X.columns,
    'coefficient': model.coef_
})
print(coeff_df)